# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffc0e4a76271587b750b2ae3553e2302655dad9478e43c6cc3f0b0a2457ecd0b5c0da7a63c875ea18aae40bad95af9dc90738c088f26dd9e5c9a27dfb41e09c8
  twitter:
    consumer_key: ijExo1SPknddqTuVZj1ZGxJ8c
    consumer_secret: zzOGmD7Jj5hAuY5SV494ajBjQONCIDr3RYaP5vjEqrnH0qeF3S

test:
  secret_key_base: 9a94484dc229431e4e005f992262da47afb83ab6c0dbcc7ae9682f52ecc820ecb65554e6e7b40ac07a3e8418c029748bcd5849168708bb15d105a384229d03a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ffc0e4a76271587b750b2ae3553e2302655dad9478e43c6cc3f0b0a2457ecd0b5c0da7a63c875ea18aae40bad95af9dc90738c088f26dd9e5c9a27dfb41e09c8
